openapi: 3.0.0
info:
  title: 'MathHub API'
  description: 'MathHub 後端 API 規格文件'
  version: '1.0.2 20250831'
  contact:
    name: 'MathHub'

servers:
  - url: 'https://mathhubbackend.zeabur.app'
    description: 'MathHub 後端環境'

# 引入通用參數和響應
components:
  parameters:
    ContentTypeHeader:
      $ref: './schemas/common.yml#/parameters/ContentTypeHeader'
    AuthorizationHeader:
      $ref: './schemas/common.yml#/parameters/AuthorizationHeader'
    IDParam:
      $ref: './schemas/common.yml#/parameters/IDParam'
    LimitParam:
      $ref: './schemas/common.yml#/parameters/LimitParam'
    SkipParam:
      $ref: './schemas/common.yml#/parameters/SkipParam'
    FilterParam:
      $ref: './schemas/common.yml#/parameters/FilterParam'
    SortParam:
      $ref: './schemas/common.yml#/parameters/SortParam'
    ProjectionParam:
      $ref: './schemas/common.yml#/parameters/ProjectionParam'

  schemas:
    # 引入通用參數
    ID:
      $ref: './schemas/common.yml#/schemas/ID'

    # 引入用戶相關 Schema
    User:
      $ref: './schemas/user.yml#/User'
    Creator:
      $ref: './schemas/user.yml#/Creator'
    LoginRequest:
      $ref: './schemas/auth.yml#/LoginRequest'
    LoginResponse:
      $ref: './schemas/auth.yml#/LoginResponse'
    RegisterRequest:
      $ref: './schemas/auth.yml#/RegisterRequest'
    RefreshTokenResponse:
      $ref: './schemas/auth.yml#/RefreshTokenResponse'

    # 引入用戶相關 Schema
    UserRequest:
      $ref: './schemas/user.yml#/UserRequest'
    UserUpdate:
      $ref: './schemas/user.yml#/UserUpdate'

    # 引入公告相關 Schema
    NoticeBoard:
      $ref: './schemas/noticeBoard.yml#/NoticeBoard'
    NoticeBoardRequest:
      $ref: './schemas/noticeBoard.yml#/NoticeBoardRequest'

    # 引入題目相關 Schema
    Question:
      $ref: './schemas/question.yml#/Question'
    QuestionRequest:
      $ref: './schemas/question.yml#/QuestionRequest'
    QuestionStatus:
      $ref: './schemas/question.yml#/QuestionStatus'
    QuestionAnswer:
      $ref: './schemas/question.yml#/QuestionAnswer'

    # 引入通用響應
    SuccessResponse:
      $ref: './schemas/common.yml#/responses/SuccessResponse'
    PaginationResponse:
      $ref: './schemas/common.yml#/responses/PaginationResponse'
    PostDataResponse:
      $ref: './schemas/common.yml#/responses/PostDataResponse'
    PatchDataResponse:
      $ref: './schemas/common.yml#/responses/PatchDataResponse'
    '400ErrorResponse':
      $ref: './schemas/common.yml#/responses/400ErrorResponse'
    '401ErrorResponse':
      $ref: './schemas/common.yml#/responses/401ErrorResponse'
    '403ErrorResponse':
      $ref: './schemas/common.yml#/responses/403ErrorResponse'
    '404ErrorResponse':
      $ref: './schemas/common.yml#/responses/404ErrorResponse'
    '500ErrorResponse':
      $ref: './schemas/common.yml#/responses/500ErrorResponse'

# API 路徑
paths:
  # 認證相關 API
  /auth/login:
    $ref: './api/authApi.yml#/login'
  # /auth/logout:
  #   $ref: './api/authApi.yml#/logout'
  # /auth/refresh:
  #   $ref: './api/authApi.yml#/refresh'
  /auth/register:
    $ref: './api/authApi.yml#/register'
  # /auth/me:
  #   $ref: './api/authApi.yml#/me'

  # 題目相關 API
  /questions:
    $ref: './api/questionApi.yml#/questions'
  /questions/{id}:
    $ref: './api/questionApi.yml#/questionsByID'
  /questions/{id}/status:
    $ref: './api/questionApi.yml#/questionsPatchStatus'

  # 管理員相關 API
  /admin/users:
    $ref: './api/userApi.yml#/users'
  /admin/users/{id}:
    $ref: './api/userApi.yml#/usersByID'

  /admin/noticeBoards:
    $ref: './api/noticeBoardApi.yml#/noticeBoards'
  # /admin/noticeBoards/{id}:
  #   $ref: './api/noticeBoardApi.yml#/noticeBoardsByID'

# API 標籤
tags:
  # - name: "認證"
  #   description: "用戶認證相關 API"
  - name: '公告'
    description: '公告相關 API'

  - name: '用戶'
    description: '用戶相關 API'

  - name: '題目'
    description: '題目相關 API'
